# Netlify configuration file
# This tells Netlify how to build and deploy the static marketing site.

[build]
  # We have no build step for our simple HTML/CSS site.
  # This command does nothing and prevents Netlify from auto-detecting Python.
  command = "rm requirements.txt && echo 'No build command needed for static site'"

  # The directory to publish, which contains our index.html.
  publish = "."